version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ubermoto
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ubermoto
      POSTGRES_DB: ubermoto
      POSTGRES_USER: uber
      POSTGRES_PASSWORD: uberpass
    ports:
      - "5432:5432"
    volumes:
      - ./data-postgres:/var/lib/postgresql/data