#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:h2:mem:ubermoto;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      properties:
#        hibernate.hbm2ddl.import_files: import.sql
#    show-sql: true
#
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:     472952533294-na3lurjorrphtudh1t3umhf0bs0suq5t.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - openid
#              - email
#              - profile
#            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
#            logging:
#              level:
#                org.springframework.security: DEBUG